"""initial

Revision ID: b3b28b9aa5bb
Revises: 
Create Date: 2026-07-23 10:56:31.486839

"""
from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision = 'b3b28b9aa5bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloaded_files',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_downloaded_files')),
    sa.UniqueConstraint('name', name='uq_downloaded_files_name')
    )
    op.create_index(op.f('ix_downloaded_files_downloaded_at'), 'downloaded_files', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_downloaded_files_name'), 'downloaded_files', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloaded_files_name'), table_name='downloaded_files')
    op.drop_index(op.f('ix_downloaded_files_downloaded_at'), table_name='downloaded_files')
    op.drop_table('downloaded_files')
    # ### end Alembic commands ###
